### ISSUE TITLE
(IMPORT FAILED): /home/kwan/ComfyUI/custom_nodes/comfy_translation_node

### ISSUE THREAD

**Issue by markawonge** [laojingwei/comfy_translation_node#1]
OS：Linux (ubuntu / Fedora)
环境：miniconda env
问题描述：导入失败，无法载入

----------start-------第一次使用------未发现translate翻译包，正在下载。。。
Collecting translate
  Using cached translate-3.6.1-py2.py3-none-any.whl (12 kB)
Collecting click (from translate)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting lxml (from translate)
  Using cached lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting requests (from translate)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting libretranslatepy==2.1.1 (from translate)
  Using cached libretranslatepy-2.1.1-py3-none-any.whl (3.2 kB)
Collecting charset-normalizer<4,>=2 (from requests->translate)
  Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->translate)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->translate)
  Using cached urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests->translate)
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl (7.9 MB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
Using cached urllib3-2.0.7-py3-none-any.whl (124 kB)
Installing collected packages: libretranslatepy, urllib3, lxml, idna, click, charset-normalizer, certifi, requests, translate
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openxlab 0.0.28 requires requests~=2.28.2, but you have requests 2.31.0 which is incompatible.

**Comment by laojingwei** [comment]
问题：Openxlab 0.0.28需要请求~=2.28.2，但您的请求2.31.0不兼容。分析：Python环境某些依赖不兼容建议：你试试重新安装openxlab依赖看看，或者更新pip版本试试参考：这个错误通常是由于Python依赖包之间存在冲突，导致pip无法正确解析依赖关系，从而无法安装或升级某些包。常见的解决方法包括：1. 清理缓存：使用`pip cache purge`命令清理pip缓存，然后再次尝试安装或升级包。2. 升级pip：使用`pip install –upgrade pip`命令升级pip到最新版本，然后再次尝试安装或升级包。3. 使用虚拟环境：使用虚拟环境来隔离不同项目之间的依赖关系，避免冲突。可以使用`venv`、`virtualenv`等工具创建虚拟环境。4. 手动安装依赖包：如果pip无法解决依赖关系，可以尝试手动安装依赖包。可以使用`pip download`命令下载依赖包的源码包，然后使用`pip install`命令手动安装依赖包。5. 解决依赖冲突：如果依赖包之间存在冲突，可以尝试手动解决冲突。可以使用`pip show`命令查看已安装的包的版本信息，然后手动安装或升级依赖包，以满足依赖关系。在解决这个问题时，可以先尝试清理缓存、升级pip等常见方法，如果还是无法解决问题，可以尝试使用`pipdeptree`等工具查看依赖关系，以便更好地定位问题发自我的iPhone------------------ Original ------------------From: MarKA  ***@***.***>Date: Tue,Nov 7,2023 5:30 PMTo: laojingwei/comfy_translation_node ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [laojingwei/comfy_translation_node] (IMPORT FAILED):/home/kwan/ComfyUI/custom_nodes/comfy_translation_node (Issue #1)
OS：Linux (ubuntu / Fedora)
环境：miniconda env
问题描述：导入失败，无法载入
----------start-------第一次使用------未发现translate翻译包，正在下载。。。
Collecting translate
Using cached translate-3.6.1-py2.py3-none-any.whl (12 kB)
Collecting click (from translate)
Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting lxml (from translate)
Using cached lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting requests (from translate)
Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting libretranslatepy==2.1.1 (from translate)
Using cached libretranslatepy-2.1.1-py3-none-any.whl (3.2 kB)
Collecting charset-normalizer<4,>=2 (from requests->translate)
Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->translate)
Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->translate)
Using cached urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests->translate)
Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl (7.9 MB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
Using cached urllib3-2.0.7-py3-none-any.whl (124 kB)
Installing collected packages: libretranslatepy, urllib3, lxml, idna, click, charset-normalizer, certifi, requests, translate
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openxlab 0.0.28 requires requests~=2.28.2, but you have requests 2.31.0 which is incompatible.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/laojingwei/comfy_translation_node/issues/1",
"url": "https://github.com/laojingwei/comfy_translation_node/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by markawonge** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opendatalab 0.0.10 requires openxlab, which is not installed.
Successfully installed certifi-2023.7.22 charset-normalizer-3.3.2 click-8.1.7 idna-3.4 libretranslatepy-2.1.1 lxml-4.9.3 requests-2.31.0 translate-3.6.1 urllib3-2.0.7
-----------end------------translate下载完成---如看到黄色提示话术，说明有些依赖是已经安装过了，只要不是error均无需在意
----------start-------------未发现tweak_keywords_CN2EN文件夹，正在处理。。。
Traceback (most recent call last):
  File "/home/kwan/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kwan/ComfyUI/custom_nodes/comfy_translation_node/__init__.py", line 320, in <module>
    init()
  File "/home/kwan/ComfyUI/custom_nodes/comfy_translation_node/__init__.py", line 26, in init
    shutil.copytree (tweak_path_bk, tweak_path)
  File "/home/kwan/miniconda3/envs/cf/lib/python3.11/shutil.py", line 559, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kwan/ComfyUI\\ComfyUI\\custom_nodes\\comfy_translation_node\\tweak_keywords_CN2EN'

Cannot import /home/kwan/ComfyUI/custom_nodes/comfy_translation_node module for custom nodes: [Errno 2] No such file or directory: '/home/kwan/ComfyUI\\ComfyUI\\custom_nodes\\comfy_translation_node\\tweak_keywords_CN2EN'



这段错误信息表明:

正在尝试导入一个翻译相关的自定义节点模块comfy_translation_node

这个模块在初始化时,尝试使用shutil.copytree拷贝文件/文件夹tweak_keywords_CN2EN

但发现这个文件/文件夹不存在,导致FileNotFoundError

原因很可能是:

tweak_keywords_CN2EN这个文件夹/文件配套资源缺失

自定义节点代码中文件夹路径写错了

解决方案:

检查自定义节点代码中文件夹路径是否正确

查看是否缺少tweak_keywords_CN2EN这个配套资源文件/文件夹

尝试从项目备份/文档中恢复这个文件/文件夹

如果无法恢复,可能需要修改节点代码,不依赖这个资源文件

联系原项目作者获取完整资源

重新构建这个资源文件/文件夹

总之,关键是找到原因导致的这个特定资源文件/文件夹缺失,然后恢复或者修改代码规避这个依赖。
